# Generated by Django 3.0.7 on 2020-06-16 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_de_marca', models.ImageField(upload_to='images/')),
                ('material', models.CharField(choices=[('Silicona', 'Silicona'), ('Termoplástico', 'Termoplástico'), ('No hay información', 'No hay información')], max_length=20)),
                ('origen', models.CharField(max_length=200)),
                ('rigidez_cuerpo', models.CharField(choices=[('Fuerte', 'Fuerte'), ('Media a Fuerte', 'Media a fuerte'), ('Media', 'Media'), ('Blanda', 'Blanda')], max_length=20)),
                ('rigidez_anillo', models.CharField(choices=[('Fuerte', 'Fuerte'), ('Media a Fuerte', 'Media a fuerte'), ('Media', 'Media'), ('Blanda', 'Blanda')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True)),
                ('talle', models.CharField(max_length=10)),
                ('ancho', models.CharField(max_length=10)),
                ('altura_con_cabito', models.CharField(max_length=10)),
                ('altura_sin_cabito', models.CharField(blank=True, max_length=10, null=True)),
                ('capacidad', models.CharField(max_length=10)),
                ('tipo_de_agarre', models.CharField(choices=[('Bolita', 'Bolita'), ('Anillo', 'Anillo'), ('Palito', 'Palito'), ('Incorporado', 'Incorporado')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminMode.Marca')),
            ],
        ),
    ]
